config/routes.rb
Rails.application.routes.draw do

  resources :jobs
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	has_many :jobs
end

app/models/industry.rb
class Industry < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :industry
	belongs_to :role
	belongs_to :experience

	validates :title, presence: true
	validates :description, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@jobs = Job.all
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.create(job_params)
		if @job.save!
			redirect_to jobs_path
		else
			redirect_to new_job_path
		end
	end 

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.update(job_params)
		if @job.save!
			redirect_to jobs_path
		else
			redirect_to edit_job_path
		end
	end

	def destroy
		@job = Job.find(params[:id])
		@job.delete
		redirect_to jobs_path
	end

	def show
		@job = Job.find(params[:id])
	end

	private

	def job_params
		params.require(:job).permit(:title, :description, :city, :state, :posted, :role_id, :industry_id, :experience_id)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :description %>
		<%= f.text_area :description, size: '60x6' %>
	</div>
	<div>
		<%= f.label :city %>
		<%= f.text_field :city %>
	</div>
	<div>
		<%= f.label :state %>
		<%= f.text_field :state %>
	</div>
	<div>
		<%= f.label :posted %>
		<%= f.date_field :posted %>
	</div>
	</div>
	<div>
		<%= f.collection_select :role_id, Role.all, :id, :role_type %>
	</div>
	<div>
		<%= f.collection_select :industry_id, Industry.all, :id, :industry_type %>
	</div>
	<div>
		<%= f.collection_select :experience_id, Experience.all, :id, :level %>
	</div>
	<div>
	<%= f.submit %>
	</div>
<% end %>


    	

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>

<%= render "form" %>

app/views/jobs/index.html.erb
<h1>RailsBridge Corp Open Jobs</h1>

<% @jobs.each do |job| %>
	<h3><%= link_to job.title, job_path(job) %></h3>
	<h5><%= link_to "Edit Posting", edit_job_path(job)%></h5>
	<h5><%= link_to "Delete Posting", job, method: :delete %></h5>

<% end %>

app/views/jobs/new.html.erb
<h1>Add a job</h1>

<%= render "form" %>

app/views/jobs/show.html.erb
<h3>Title: <%= @job.title %></h3>
<p>Description: <%= @job.description %></p>
<p>City and State: <%= @job.city %>, <%= @job.state %></p>

<p>Job Role: <%= @job.role.role_type %></p>
<p>Industry: <%= @job.industry.industry_type %></p>
<p>Experience Level: <%= @job.experience.level %></p>

<p>Posted Date: <%= @job.posted %></p>

<div>
	<%= link_to "Edit Posting", edit_job_path(@job)%>
	<%= link_to "Delete Posting", @job, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<div class="left-nav">
		<ul>
			<li><%= link_to "Home", jobs_path %></li>
		</ul>
	</div>
	<div class="right-nav">
		<ul>
			<li><%= link_to "Add Job", new_job_path %></li>
		</ul>
	</div>
	<div class="clearfix"></div>
</header>

<%= yield %>

</body>
</html>